## NUMPY 
  - SHORT OF NUMERICICAL PYTHON
  - FOUNDATIONAL PACKAGE FOR NUMERICAL COMPUTING IN PYTHON
  - PROVIDES NDARRAYS OBJECT WHICH IS AN EFFICIENT MULTIDIMENSTUINAL ARRAYS PROVIDNG FAST ARRAY ORIENTED OPERATIONS
  - PROVIDES A LOT OF FUNCTIONS.
    

# 1. What is NumPy?

Answer:

NumPy (Numerical Python) is a Python library used for numerical computing. It provides a powerful N-dimensional array object and mathematical functions  on large datasets.



# 2. Why is NumPy faster than Python lists?

Answer:

NumPy is faster because:

It stores elements in contiguous memory.
All elements have the same data type.
It performs operations using optimized C code.
It supports vectorized operations, avoiding Python loops.

# 3 Difference between Python List and NumPy Array
Python List	                      NumPy Array
Can store different data types	 Stores same data type
Slower	                         Faster
More memory usage	               Less memory usage
Doesn't support vectorized operations	Supports vectorized operations


# 4  What is Vectorization?

Answer:

Vectorization means performing operations on an entire array without writing loops.

# 5 What are shape, size, and ndim?

 # shape

Returns rows and columns.


# size

Total number of elements.

# ndim

Number of dimensions.

# 6. Difference between reshape() and resize()
 # reshape()

Returns a new array with a different shape.

Original array remains unchanged.


# resize()

Changes the original array itself.

# 7. Explain axis=0 and axis=1

 # axis=0

Works column-wise.

# axis=1

Works row-wise.

# 8. Difference between concatenate(), hstack(), and vstack()

# concatenate
np.concatenate((a,b), axis=0)

Flexible because you choose the axis.

# hstack

Joins horizontally.

# vstack

Joins vertically.


 # 9 What is Boolean Indexing?

Selecting elements based on a condition.

a = np.array([10,20,30,40])

a[a>20]


# 10. What is Broadcasting?

Broadcasting allows NumPy to perform arithmetic on arrays of different but compatible shapes.

Example

a = np.array([1,2,3])

a + 10


# 11 What is Fancy Indexing?

Access elements using lists or arrays of indices.


# 12 Why is NumPy important for Pandas and Machine Learning?

"NumPy is the backbone of data science because Pandas, Scikit-learn, SciPy, and many other libraries rely on NumPy arrays for fast and efficient numerical computation.

In [29]:
import numpy as np

## CREATING ND ARRAYS  
  - CREATING NDARRAYS FROM AN OBJECT 

In [109]:
l1 = [1,2,3,4,5]       # list 
a1 = numpy.array(l1)
a1 

NameError: name 'numpy' is not defined

In [5]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [6]:
type(a1)

numpy.ndarray

In [10]:
t1 = (1,2,3,4,5)    # tuple
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array(range(2,11,2))
a1

array([ 2,  4,  6,  8, 10])

In [14]:
a1.ndim    # to check the dimentions    it has single [ bracket so it is one dimesion

1

In [1]:
a1.shape       #  (5,)   why , this interview Q 


NameError: name 'a1' is not defined

In [16]:
a1 = np.array([[1,2,3],[4,5,6]])
a1.shape


(2, 3)

In [17]:
a1.ndim

2

In [6]:
ab = np.arange(9)
ab
ab.dtype          # it check the type 

dtype('int64')

In [18]:
a1 = np.array([[[1,2,3],[4,5,6]]])
a1.shape
a1

array([[[1, 2, 3],
        [4, 5, 6]]])

In [19]:
a1.ndim

3

In [20]:
a1.shape

(1, 2, 3)

In [21]:
a1 = np.array([[[[1,2,3],[4,5,6]]]])
a1.shape

(1, 1, 2, 3)

In [22]:
a1 = np.array([[[[[1,2,3],[4,5,6]]]]])
a1.shape

(1, 1, 1, 2, 3)

In [8]:
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a1.shape 

(2, 2, 2)

In [9]:
a1.ndim 

3

In [16]:
a1 = np.array([[[1.1,2],[3,4]],[[5,6.6],[7.25,8]]]) 
a1.dtype 

dtype('float64')

In [3]:
a1 = np.array([[[1.1,2],[3,4]],[[5,6.6],[7.25,8]]]) 
a1.shape

(2, 2, 2)

#  change the data type

In [4]:
a1 = np.array([[[1.1,2],[3,4]],[[5,6.6],[7.25,8]]]) 
b1 = a1.astype(int)    ## it can change the type ....
b1


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## CREATING NDARRAYS OF ONES ,ZEROES AND SPECIFIC VALUES  

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones((5,5) ,dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.ones((3,2,4) ,dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [9]:
a= np.zeros((4,2,5))
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [37]:
np.full((4,5),fill_value=2 ,dtype=int)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [38]:
np.eye(5)           # identity matrix.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
b= np.full((4,5) ,fill_value=5)
np.fill_diagonal(b,4)
b

array([[4, 5, 5, 5, 5],
       [5, 4, 5, 5, 5],
       [5, 5, 4, 5, 5],
       [5, 5, 5, 4, 5]])

# OPERATIONS ON NDARRAYS

In [39]:
l = [1,2,3,4,5]
l + 2

TypeError: can only concatenate list (not "int") to list

In [19]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [42]:
a + 2      # this is main use of numpy

array([3, 4, 5, 6, 7])

In [22]:
b = np.array([4,5,6,7,8]) 

In [46]:
a + b

array([ 5,  7,  9, 11, 13])

In [47]:
a

array([1, 2, 3, 4, 5])

In [48]:
a - b

array([-3, -3, -3, -3, -3])

In [49]:
a * b

array([ 4, 10, 18, 28, 40])

In [50]:
a / b

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

In [51]:
b / a

array([4.  , 2.5 , 2.  , 1.75, 1.6 ])

In [20]:
a % 2

array([1, 0, 1, 0, 1])

In [23]:
a > b


array([False, False, False, False, False])

In [24]:
a 

array([1, 2, 3, 4, 5])

In [25]:
b

array([4, 5, 6, 7, 8])

In [26]:
a ** b 

array([     1,     32,    729,  16384, 390625])

In [27]:
a // b

array([0, 0, 0, 0, 0])

## INDEXING AND SLICING IN SINGLE DIMENSION ARRAY   

In [56]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a[-1]

np.int64(9)

In [61]:
a[-3:-7:3]

array([], dtype=int64)

 ## RESHAPE  AND TRANSPOSE 

In [62]:
a = np.arange(16)

In [63]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [64]:
a.shape

(16,)

In [65]:
a.ndim

1

In [67]:
a = a.reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
a = a.reshape((8,2))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [71]:
a = a.reshape((2,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [72]:
a = a.reshape((2,2,2,2))
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [75]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
a.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

 # ONE DIMENSION ARRAY

# FUNCTIONS  

In [2]:
a = np.array([2,3,6,8,9,4,5,1,7])
a

array([2, 3, 6, 8, 9, 4, 5, 1, 7])

In [3]:
a.sort()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382])

In [6]:
np.abs([-1,-2,4,-5,6,-8])

array([1, 2, 4, 5, 6, 8])

In [7]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [8]:
np.subtract([1,2,3],[4,5,6])

array([-3, -3, -3])

In [9]:
np.multiply([1,2,3],[4,5,6])

array([ 4, 10, 18])

In [10]:
np.divide([1,2,3],[4,5,6])

array([0.25, 0.4 , 0.5 ])

In [11]:
np.minimum(a1,a2)

NameError: name 'a1' is not defined

In [28]:
a1 = np.array([2,1,3,6,3,4])
a2 = np.array([3,4,2,5,8,5]) 

In [38]:
np.sum(a1)   # sum tak one argument only 

np.int64(19)

In [39]:
# if we want to add
a1 + a2

array([ 5,  5,  5, 11, 11,  9])

In [40]:
np.var(a1)

np.float64(2.4722222222222223)

In [41]:
np.std(a1)

np.float64(1.5723301886761007)

In [34]:
 np.minimum(a1,a2)

array([2, 1, 2, 5, 3, 4])

In [15]:
np.maximum(a1,a2)

array([3, 4, 3, 6, 8, 5])

In [16]:
np.greater(a1,a2)

array([False, False,  True,  True, False, False])

In [17]:
np.greater(a2,a1)

array([ True,  True, False, False,  True,  True])

In [18]:
np.less(a1,a2)

array([ True,  True, False, False,  True,  True])

In [19]:
np.less(a2,a1)

array([False, False,  True,  True, False, False])

In [22]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [23]:
a1.mean()

np.float64(10.0)

In [24]:
np.median(a1)

np.float64(10.0)

In [26]:
a1.min()

np.int64(0)

In [27]:
a1.max()

np.int64(20)

In [28]:
a1.sum()

np.int64(210)

## TWO DIMENSION ARRAY 

In [30]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [32]:
a.shape

(8, 8)

a.min()

In [34]:
a.mean()

np.float64(31.5)

In [36]:
a.mean(axis=0)    #  axis=0 column-wise (top to bottom). 

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [38]:
a.mean(axis=1)   # Result for each row

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [39]:
a.max()

np.int64(63)

In [40]:
a.max(axis=1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [41]:
a.max(axis=0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [42]:
a.min(axis=1)

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [43]:
a.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
x = np.array([1,2,4,3,3,4])
x

array([1, 2, 4, 3, 3, 4])

In [16]:
np.argmax(x)     # returns the index (position) of the largest element in an array.

np.int64(2)

In [49]:
np.argmin(x)

np.int64(0)

In [48]:
a = np.arange(9).reshape((3,3))
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
np.argmax(a)

np.int64(8)

In [51]:
np.argmin(a)

np.int64(0)

In [53]:
np.argmax(a,axis = 0)

array([2, 2, 2])

In [54]:
np.argmax(a,axis = 1)

array([2, 2, 2])

In [55]:
np.argmin(a,axis = 0)

array([0, 0, 0])

In [56]:
np.argmin(a,axis = 1)

array([0, 0, 0])

In [56]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
a =np.array([2,1,5,4,3,5,6,7,3,9,2,3]).reshape(3,4)
a


array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [58]:
b = np.insert(a,1,[5,1,6,7],axis=0)
b

array([[ 0,  1,  2,  3],
       [ 5,  1,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
c = np.insert(a,1,[5,1,6,7],axis=1) 
c

array([[ 0,  5,  1,  2,  3],
       [ 4,  1,  5,  6,  7],
       [ 8,  6,  9, 10, 11],
       [12,  7, 13, 14, 15]])

In [59]:
a = np.array([10,20,30])
b = np.append(a,[40,50])
b

array([10, 20, 30, 40, 50])

In [61]:
b=np.delete(a,1)
b

array([10, 30])

In [63]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))   # vertically stack

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.hstack((a,b))    # horizonatally 


array([1, 2, 3, 4, 5, 6])

In [68]:
# spliting

a = np.array([10,20,30,40,50,60])
np.split(a,3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [70]:
np.split(a,2)

[array([10, 20, 30]), array([40, 50, 60])]

In [59]:
np.argmax(a)

np.int64(9)

In [60]:
np.argmax(a,axis=0)

array([1, 2, 1, 1])

In [61]:
np.argmax(a,axis=1)

array([2, 3, 1])

In [63]:
a1 = a.reshape(1,3,4)
a1

array([[[2, 1, 5, 4],
        [3, 5, 6, 7],
        [3, 9, 2, 3]]])

In [66]:
a2 = a1.squeeze()     # squeeze() removes dimensions of size 1 from an array  but first size should be 1
a2

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [67]:
a1 = np.arange(5)
a2 = np.arange(5,10)
print(a1)
print(a2)


[0 1 2 3 4]
[5 6 7 8 9]


In [68]:
a1 

array([0, 1, 2, 3, 4])

In [69]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(5)
b = np.arange(5,10)

In [18]:
a

array([0, 1, 2, 3, 4])

In [19]:
b 

array([5, 6, 7, 8, 9])

In [21]:
np.concatenate((a,b)) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.concatenate((a,b ),axis=1) 

AxisError: axis 1 is out of bounds for array of dimension 1

In [70]:
np.concatenate((a2,a1))

array([5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [71]:
a1 = a1.reshape(1,5)
a1


array([[0, 1, 2, 3, 4]])

In [72]:
a2 = a2.reshape(1,5)
a2

array([[5, 6, 7, 8, 9]])

In [74]:
np.concatenate((a2,a1),axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [75]:
np.concatenate((a2,a1),axis=1)

array([[5, 6, 7, 8, 9, 0, 1, 2, 3, 4]])

## RANDOM NUMBERS  

In [5]:
np.random.randint(1,100) 

26

In [77]:
np.random.randint(1,100,10)

array([81, 33, 12, 55,  6, 77, 48, 81, 89, 36], dtype=int32)

In [78]:
np.random.randint(1,100,(10,10))

array([[73, 66, 13, 22, 32, 71, 68, 89, 92, 24],
       [82, 94, 50, 31,  5, 27, 57, 46, 90,  1],
       [94, 60, 36, 65, 65, 63, 83, 94, 53, 83],
       [99,  7, 39, 20, 78, 40, 99, 53, 98, 55],
       [35, 93, 61, 10, 66, 87, 27, 90, 71, 32],
       [ 5, 31, 16, 72, 44, 62, 42, 14, 38, 42],
       [60, 32, 91, 38,  5, 87, 83, 29, 25, 11],
       [42, 33, 35, 29, 57, 88, 51, 67, 61, 99],
       [90, 96, 12, 10, 77, 34, 35, 94, 62, 31],
       [45, 46, 63, 86, 10, 25, 12, 83, 10, 17]], dtype=int32)

In [79]:
np.random.rand(10)

array([0.99088231, 0.50137119, 0.46286085, 0.5767781 , 0.77189716,
       0.05287002, 0.8312548 , 0.27679499, 0.18723169, 0.21066069])

In [80]:
np.random.rand(10,5)

array([[0.20833644, 0.25835619, 0.06516903, 0.8315301 , 0.16215359],
       [0.29727173, 0.08533473, 0.90273085, 0.22001131, 0.09465514],
       [0.48898711, 0.35708471, 0.31206066, 0.8404084 , 0.01630439],
       [0.10106349, 0.23387888, 0.49826998, 0.51911324, 0.95825989],
       [0.85776243, 0.25566075, 0.59058399, 0.66968949, 0.24385871],
       [0.440497  , 0.96081238, 0.31555538, 0.04278289, 0.51270996],
       [0.28007978, 0.52550584, 0.99383353, 0.56546452, 0.52427848],
       [0.32041943, 0.57211664, 0.29386968, 0.10252687, 0.58256021],
       [0.13541944, 0.93966289, 0.28840632, 0.30054391, 0.48518915],
       [0.33547415, 0.67654054, 0.86208123, 0.23487011, 0.98224723]])

In [82]:
np.random.randn(10)     # randn will give negative no also...

array([ 1.52127336, -1.2092462 , -1.08538576, -1.08316377, -0.81949625,
        0.51643453, -0.07615174, -1.18333896, -0.24105626,  0.06935008])

# CONDITIONAL INDEXING  

In [83]:
a = np.random.randint(1,100,(8,8))

In [84]:
a

array([[49, 35, 77, 99, 35,  6, 32, 74],
       [50, 23,  3, 47, 69, 19, 75, 30],
       [26,  2, 55, 55, 86, 85, 63, 24],
       [85, 80, 98, 98, 39, 97, 41, 57],
       [78, 34, 53,  3, 92, 96, 21, 89],
       [57, 57, 23, 13,  1, 55, 69, 15],
       [97, 97, 31, 83,  3,  3, 90, 75],
       [53, 63, 83, 35,  6, 70, 83, 73]], dtype=int32)

In [85]:
a > 50

array([[False, False,  True,  True, False, False, False,  True],
       [False, False, False, False,  True, False,  True, False],
       [False, False,  True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True, False,  True, False,  True],
       [ True, False,  True, False,  True,  True, False,  True],
       [ True,  True, False, False, False,  True,  True, False],
       [ True,  True, False,  True, False, False,  True,  True],
       [ True,  True,  True, False, False,  True,  True,  True]])

In [86]:
a[a>50]

array([77, 99, 74, 69, 75, 55, 55, 86, 85, 63, 85, 80, 98, 98, 97, 57, 78,
       53, 92, 96, 89, 57, 57, 55, 69, 97, 97, 83, 90, 75, 53, 63, 83, 70,
       83, 73], dtype=int32)

#  SLICING IN MULTIDIMENSION  ARRAY

In [8]:
a = np.random.randint(1,100,(10,10))

In [88]:
a

array([[40, 29, 24, 10, 38, 53, 11, 55, 93, 11],
       [94, 39, 25, 57, 27, 76, 44, 44, 85, 37],
       [36, 94, 38, 83,  6, 99, 86, 85, 96, 53],
       [62, 77, 37, 26, 72, 93, 95,  4, 93, 14],
       [54, 97, 25,  4, 31, 92, 91, 52, 53, 90],
       [71, 93, 44, 24, 84, 58, 16, 58, 35, 30],
       [94, 32, 32, 36, 84, 85, 47,  1, 49, 94],
       [97, 26, 62, 43, 64, 31, 65, 97, 43, 67],
       [22, 62, 39,  8, 52, 90, 88, 83, 47, 16],
       [44, 64, 14, 58, 72, 72, 69, 72, 93,  2]], dtype=int32)

In [91]:
a[1]

array([94, 39, 25, 57, 27, 76, 44, 44, 85, 37], dtype=int32)

In [93]:
a[1][4]

np.int32(27)

In [89]:
a[(1,4)]

np.int32(27)

In [90]:
a[1,4]

np.int32(27)

In [10]:
a[2:4,:]
a

array([[ 2, 84, 67, 59,  6, 82,  1, 53, 83, 49],
       [67, 51,  7, 22, 14,  7, 60, 14, 83,  1],
       [82, 99, 74,  7, 18, 27, 77, 79, 75, 97],
       [61, 25, 66, 55, 43, 95, 65, 14, 12, 63],
       [52, 92, 84, 37,  6, 93, 65, 14, 78, 52],
       [34, 73, 11, 37, 85,  6, 42, 81, 22, 29],
       [91, 88, 91, 79, 87, 72, 92, 62, 19,  8],
       [50,  1, 61, 35, 54, 45, 67, 25, 53, 40],
       [ 3, 57, 48, 17, 47, 82, 94, 86, 16, 76],
       [99, 15, 53, 75, 30, 49, 29, 73, 60, 72]], dtype=int32)

In [11]:
a

array([[ 2, 84, 67, 59,  6, 82,  1, 53, 83, 49],
       [67, 51,  7, 22, 14,  7, 60, 14, 83,  1],
       [82, 99, 74,  7, 18, 27, 77, 79, 75, 97],
       [61, 25, 66, 55, 43, 95, 65, 14, 12, 63],
       [52, 92, 84, 37,  6, 93, 65, 14, 78, 52],
       [34, 73, 11, 37, 85,  6, 42, 81, 22, 29],
       [91, 88, 91, 79, 87, 72, 92, 62, 19,  8],
       [50,  1, 61, 35, 54, 45, 67, 25, 53, 40],
       [ 3, 57, 48, 17, 47, 82, 94, 86, 16, 76],
       [99, 15, 53, 75, 30, 49, 29, 73, 60, 72]], dtype=int32)

In [104]:
a[2][2: :3]

array([38, 99, 96], dtype=int32)

In [106]:
a[2:9:3,2:9:3]

array([[38, 99, 96],
       [44, 58, 35],
       [39, 90, 47]], dtype=int32)

In [16]:
a[5:6:1,4:6:1] 

array([[85,  6]], dtype=int32)

# HANDLIN THE MISSING VALUES
 - np.isnan     detect missing values
 - np.nan_to_num()       # not a number 
 - np.isinf      # to dectect the infinte value 

In [75]:
a=np.array([1,2,np.nan,4,np.nan,6])
np.isnan(a)

array([False, False,  True, False,  True, False])

In [77]:
       #  np.nan_to_num()  

In [82]:
a=np.array([1,2,np.nan,4,np.nan,6])
ca = np.nan_to_num(a)          # default value is 0
ca

array([1., 2., 0., 4., 0., 6.])

In [81]:
ca = np.nan_to_num(a,nan=15)
ca

array([ 1.,  2., 15.,  4., 15.,  6.])

In [83]:
a = np.array([1,2,np.inf,4,-np.inf,6])
np.isinf(a)

array([False, False,  True, False,  True, False])

In [28]:
np.nan_to_num(a,posinf=1000, neginf=-1000) 

array([0, 1, 2, 3, 4])